# Indexing & Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [3]:
print(arr[0])

10


In [4]:
print(arr[2])

30


In [5]:
print(arr[-1])

50


In [6]:
print(arr[-2])

40


In [7]:
arr[1:4]

array([20, 30, 40])

In [8]:
arr[:3]

array([10, 20, 30])

In [9]:
arr[2:]

array([30, 40, 50])

In [10]:
arr[::2]

array([10, 30, 50])

In [11]:
arr[::-1]

array([50, 40, 30, 20, 10])

In [12]:
arr[0] = 100
arr

array([100,  20,  30,  40,  50])

In [13]:
arr[1:3] = [200, 300]
arr

array([100, 200, 300,  40,  50])

In [14]:
slice_arr = arr[3:5]
slice_arr

array([40, 50])

In [15]:
slice_arr[0] = 400
arr

array([100, 200, 300, 400,  50])

In [16]:
slice_arr = arr[3:5].copy()
slice_arr[1] = 500

In [17]:
arr

array([100, 200, 300, 400,  50])

In [18]:
slice_arr

array([400, 500])