# Numpy with Jupyter

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

# Basic Array Operations

In [3]:
arr * 2

array([ 20,  40,  60,  80, 100])

In [4]:
data = np.array([
    [65, 170],
    [72, 180],
    [58, 160],
    [80, 175]
])
data

array([[ 65, 170],
       [ 72, 180],
       [ 58, 160],
       [ 80, 175]])

In [5]:
means = data.mean(axis=0)
means

array([ 68.75, 171.25])