### Data Exploration with NumPy

In [1]:
import numpy as np

### Sales Data, 7 Days, 3 Products

In [2]:
sales_data = np.array([
    [120, 95, 200],
    [130, 100, 210],
    [125, 90, 190],
    [140, 110, 220],
    [135, 105, 215],
    [145, 115, 230],
    [150, 120, 240]
])
sales_data

array([[120,  95, 200],
       [130, 100, 210],
       [125,  90, 190],
       [140, 110, 220],
       [135, 105, 215],
       [145, 115, 230],
       [150, 120, 240]])

In [3]:
sales_data.shape

(7, 3)

#### Total Sales Per Product

In [4]:
total_per_product = sales_data.sum(axis=0)
total_per_product

array([ 945,  735, 1505])

#### Total Sales Per Day

In [5]:
total_per_day = sales_data.sum(axis=1)
total_per_day

array([415, 440, 405, 470, 455, 490, 510])

In [6]:
max_day_sales = total_per_day.max()
print(max_day_sales)

510


In [7]:
best_day_index = total_per_day.argmax()
print(best_day_index)

6


#### Average Sales Per Product

In [8]:
avg_per_product = sales_data.mean(axis=0)
print(avg_per_product)

[135. 105. 215.]


In [ ]:
best_product_index = total_per_product.argmax()
print(best_product_index)