# Vectorization in Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 6, 10, 15, 21])
arr

array([ 1,  3,  6, 10, 15, 21])

In [4]:
res = arr + 10
res

array([11, 13, 16, 20, 25, 31])

In [5]:
def arr_square(x):
    return x*x
sq_fun = np.vectorize(arr_square)

In [6]:
sq_fun(arr)

array([  1,   9,  36, 100, 225, 441])