# Multi-dimensional Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
print(arr[1,2])

7


In [4]:
print(arr[1, :])

[5 6 7 8]


In [5]:
arr[:, 3]

array([ 4,  8, 12])

In [6]:
arr[1:3, 1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [7]:
arr[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [8]:
arr[-2:, -3:]

array([[ 6,  7,  8],
       [10, 11, 12]])