# Dealing with Missing Values

In [1]:
import numpy as np

In [2]:
data = [10, 20, None, 40, '', 60, None, 80]
data

[10, 20, None, 40, '', 60, None, 80]

In [3]:
arr = np.array(data)
arr

array([10, 20, None, 40, '', 60, None, 80], dtype=object)

In [4]:
cleaned_data = [np.nan if(x is None or x == '') else x for x in data]
cleaned_data

[10, 20, nan, 40, nan, 60, nan, 80]

In [8]:
arr = np.array(cleaned_data, dtype=float)
arr

array([10., 20., nan, 40., nan, 60., nan, 80.])

In [9]:
arr == np.nan

array([False, False, False, False, False, False, False, False])

In [ ]:
missing_val = np.isnan(arr)
missing_val