# Conditional Based Operations - Pt 2

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 25, 30, 45, 50, 15])
arr

array([10, 25, 30, 45, 50, 15])

In [4]:
condition = arr > 20
condition

array([False,  True,  True,  True,  True, False])

In [8]:
result = arr[(arr < 20) | (arr > 40)]
result

array([10, 45, 50, 15])

In [9]:
res = np.where(arr < 20, "low", "high")
res

array(['low', 'high', 'high', 'high', 'high', 'low'], dtype='<U4')

In [10]:
print(np.argwhere(arr > 25))

[[2]
 [3]
 [4]]


In [ ]:
arr_2d = np.array([[1,2,3], 
                   [4,5,6]])
np.argwhere(arr_2d > 2)