# Stacking of Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.vstack([arr1, arr2])
res

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
res = np.hstack([arr1, arr2])
res

array([1, 2, 3, 4, 5, 6])

In [4]:
res = np.stack([arr1, arr2], axis=1)
res

array([[1, 2, 3],
       [4, 5, 6]])