# Conditional Based Operations - Pt 1

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 25, 30, 45, 50, 15])
arr

array([10, 25, 30, 45, 50, 15])

In [4]:
condition = arr > 20
condition

array([False,  True,  True,  True,  True, False])

In [8]:
result = arr[(arr < 20) | (arr > 40)]
result

array([10, 45, 50, 15])