### Data Exploration with NumPy

In [1]:
import numpy as np

### Sales Data, 7 Days, 3 Products

In [2]:
sales_data = np.array([
    [120, 95, 200],
    [130, 100, 210],
    [125, 90, 190],
    [140, 110, 220],
    [135, 105, 215],
    [145, 115, 230],
    [150, 120, 240]
])
sales_data

array([[120,  95, 200],
       [130, 100, 210],
       [125,  90, 190],
       [140, 110, 220],
       [135, 105, 215],
       [145, 115, 230],
       [150, 120, 240]])

In [3]:
sales_data.shape

(7, 3)

#### Total Sales Per Product

In [4]:
total_per_product = sales_data.sum(axis=0)
total_per_product

array([ 945,  735, 1505])

#### Total Sales Per Day

In [5]:
total_per_day = sales_data.sum(axis=1)
total_per_day

array([415, 440, 405, 470, 455, 490, 510])

In [6]:
max_day_sales = total_per_day.max()
print(max_day_sales)

510


In [7]:
best_day_index = total_per_day.argmax()
print(best_day_index)

6


#### Average Sales Per Product

In [8]:
avg_per_product = sales_data.mean(axis=0)
print(avg_per_product)

[135. 105. 215.]


In [9]:
best_product_index = total_per_product.argmax()
print(best_product_index)

2


#### Sales Values Greater Than 130

In [10]:
high_sales = sales_data[sales_data > 130]
high_sales

array([200, 210, 190, 140, 220, 135, 215, 145, 230, 150, 240])

In [11]:
count_high_sales = (sales_data > 130).sum()
print(count_high_sales)

11


In [12]:
total_per_day = sales_data.sum(axis=1)
total_per_day

array([415, 440, 405, 470, 455, 490, 510])

#### Days with Total Sales Above 400

In [14]:
good_days = total_per_day > 400
good_days

array([ True,  True,  True,  True,  True,  True,  True])

In [15]:
total_per_day[good_days]

array([415, 440, 405, 470, 455, 490, 510])

In [16]:
print(good_days.sum())

7


#### Product 1 Sales Analysis

In [17]:
product_1_sales = sales_data[:,0]
product_1_sales

array([120, 130, 125, 140, 135, 145, 150])

In [18]:
product_1_avg = product_1_sales.mean()
print(product_1_avg)

135.0


In [19]:
above_avg_days = product_1_sales > product_1_avg
above_avg_days

array([False, False, False,  True, False,  True,  True])

In [20]:
product_1_sales[above_avg_days]

array([140, 145, 150])

In [ ]:
percentage = (above_avg_days.sum()/ len(product_1_sales)) * 100
print(percentage)