# Masking Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([10,15,20,25,30,35,40])
arr

array([10, 15, 20, 25, 30, 35, 40])

In [4]:
mask = arr > 20
mask

array([False, False, False,  True,  True,  True,  True])

In [5]:
res = arr[mask]
res

array([25, 30, 35, 40])

In [6]:
even_mask = arr % 2 == 0
print(even_mask)
print(arr[even_mask])

[ True False  True False  True False  True]
[10 20 30 40]


In [ ]:
mask = arr > 25
arr[mask] = 0
arr