# Repeat & Tile in NumPy Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
arr_repeat = np.repeat(arr, [2, 3, 1])
arr_repeat

array([1, 1, 2, 2, 2, 3])

In [5]:
arr_tile = np.tile(arr, 2)
arr_tile

array([1, 2, 3, 1, 2, 3])

In [ ]:
arr = np.array([0,1])
matrix = np.tile(arr, (3,2))
matrix